"""
smiles2group のコマンドラインインターフェース。
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from smiles2group.smiles2group import smiles_to_group_data


def _numpy_repr(arr) -> str:
    return "np.array(" + repr(arr.tolist()) + ", dtype=float)"


def emit_group_plugin(data: dict, class_name: str = "Group") -> str:
    """Group プラグインの Python ソースを生成する。"""
    sites = data["sites"]
    labels = data["labels"]
    bonds = data["bonds"]
    name = data["name"]

    lines = [
        "# Generated by smiles2group. GenIce3 group plugin.",
        "import genice3.group",
        "import numpy as np",
        "",
        "",
        "class Group(genice3.group.Group):",
        "    def __init__(self):",
        f"        super().__init__(",
        f"            sites={_numpy_repr(sites)},",
        f"            labels={labels!r},",
        f"            bonds={bonds!r},",
        f"            name={name!r},",
        "        )",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="SMILES から GenIce3 Group プラグイン用の原子配置を生成する（RDKit 使用）"
    )
    parser.add_argument(
        "smiles",
        type=str,
        help="SMILES 文字列。結合点を [*] で書ける（例: [*]CCCC）。[*] がある場合は anchor は省略可。",
    )
    parser.add_argument(
        "anchor",
        type=int,
        nargs="?",
        default=None,
        help="アンカー原子の 0-based インデックス。[*] がない場合に必要。",
    )
    parser.add_argument(
        "--z-neighbor",
        type=int,
        default=None,
        metavar="IDX",
        help="z 軸方向にする隣接原子のインデックス（省略時は最初の隣接）",
    )
    parser.add_argument(
        "--name",
        type=str,
        default=None,
        help="Group の名前（省略時は SMILES ベースの簡易名）",
    )
    parser.add_argument(
        "-o", "--output",
        type=Path,
        default=None,
        help="出力 .py ファイルパス（省略時は stdout）",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=0,
        help="3D 埋め込みの乱数シード",
    )
    args = parser.parse_args()

    try:
        data = smiles_to_group_data(
            args.smiles,
            anchor_atom_index=args.anchor,
            z_neighbor_index=args.z_neighbor,
            name=args.name,
            embed_seed=args.seed,
        )
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1

    src = emit_group_plugin(data)
    if args.output is not None:
        args.output.write_text(src, encoding="utf-8")
        print(f"Wrote {args.output}", file=sys.stderr)
    else:
        print(src)
    return 0


if __name__ == "__main__":
    sys.exit(main())
